# Stage 1: Build the React app
FROM node:20-alpine as build
ARG VITE_SERVER_API_V1
ENV VITE_SERVER_API_V1=${VITE_SERVER_API_V1}
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve the React app using Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
